### ISSUE TITLE
Добавить больше абстракции. Выделить отдельно хранилище.

### ISSUE THREAD

**Issue by alexeev-dauwalter** [SofiaMur/Todo-App#3]
TaskData не должн знать о том, как сохранять. Он должен только знать какой метод сохраняет и достаёт

**Comment by SofiaMur** [comment]
Выделил такие классы, как: 
- Storage, который отвечает за сохранение и извлечение данных; 
- ObserverManager, который используется для управления наблюдателями; 
- ItemCreator, который отвечает за создание элементов; 
- EventManager, который управляет действиями пользователя.
